name: meshflow
channels: [pytorch, conda-forge, defaults]
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1  # adjust to your driver
  - numpy
  - scipy
  - pyyaml
  - tqdm
  - trimesh
  - open3d
  - pip
  - pip:
      - wandb